export enum RabbitMQ {
  TipoFlujoProcesoQueue = 'tipoflujoprocesos',
}

export enum TipoFlujoProcesoMSG {
  CREATE = 'CREATE_PROCESO_TIPOFLUJOPROCESO',
  FIND_ALL = 'FIND_PROCESO_TIPOFLUJOPROCESOS',
  FIND_ONE = 'FIND_PROCESO_TIPOFLUJOPROCESO',
  UPDATE = 'UPDATE_PROCESO_TIPOFLUJOPROCESO',
  DELETE = 'DELETE_PROCESO_TIPOFLUJOPROCESO',
}
